safe-global/safe-react-components

.travis.yml
travis/prepare_production_deployment.sh

Add Travis CI configuration and deployment scripts.
CI is enabled on master branch, development branch, on tagged commits.

Add travis CI config and scripts

---

src/utils/modals/GenericModal/index.tsx
src/utils/modals/ManageListModal/ManageListModal.stories.tsx
src/utils/modals/ManageListModal/index.tsx

Fix modal width and truncate description text when is too long.

Manage list modal

---

src/inputs/Button/button.stories.tsx
src/inputs/Button/index.tsx
src/navigation/Stepper/DotStep.tsx
src/navigation/Stepper/index.tsx

-  Check icon alignment
- Steps numeration @Agupane 
Related to Gnosis/Safe-react#957

fix check icon alignment and steps numeration

---

package.json
src/inputs/Select/index.tsx
src/utils/modals/GenericModal/index.tsx
yarn.lock

This PR add some design improvements to GenericModal Component, TextField, Select
Next steps on Generic Modal:
Next steps on TextFields:
Next steps on Select:

Fixes on components for tx-builder

---

LICENSE.md
package.json
src/inputs/Button/button.stories.tsx
src/inputs/Button/index.tsx
src/inputs/ButtonLink/index.tsx
src/inputs/Select/index.tsx
src/navigation/Stepper/DotStep.tsx
src/navigation/Stepper/index.tsx
src/utils/modals/GenericModal/index.tsx
src/utils/modals/ManageListModal/ManageListModal.stories.tsx
src/utils/modals/ManageListModal/index.tsx
yarn.lock

**Fixes**:
- Manage list modal (https://github.com/gnosis/safe-react-components/pull/6)
- Stepper component steps numeration and check icon alignment (https://github.com/gnosis/safe-react-components/pull/9)
- Generic modal, TextFields, Select (https://github.com/gnosis/safe-react-components/pull/11)
**Misc**:
- Added licences (https://github.com/gnosis/safe-react-components/pull/2)

new release 0.1.3

---

.travis.yml
travis/deploy_pull_request.sh

To make it easier to test new pull requests

Configure testing environments for pull requests

---

src/inputs/TextField/index.tsx

Fix positioning of end-InputAdornment in TextField component

Fix: Input Adornment was using wrong position

---

.github/workflows/lint.yml

This PR:
- adds github action for eslint

Add github action for eslint

---

src/dataDisplay/Divider/divider.stories.tsx
src/dataDisplay/Divider/index.tsx
src/utils/modals/ManageListModal/ManageListModal.stories.tsx
src/utils/modals/ManageListModal/index.tsx

Following Mikhail's idea, in the future, this component should be moved to safe-react repo.

Feature: Add delete option to Managelist component

---

src/dataDisplay/Text/index.tsx
src/dataDisplay/Text/text.stories.tsx

This Pull Request adds a prop `isParagraph` to `Text` component.
When `isParagraph` (default true) Text is wrapped into a  `<p>` element.
When `isParagraph` is false, Text is Wrapped into a `<span>` element.

feature: [Text] Add isParagraph props

---

src/utils/modals/GenericModal/index.tsx
src/utils/modals/ManageListModal/index.tsx

This prop was producing an undesired effect when hovering buttons in the Manage List modal.

Remove GenericModal title props

---

src/dataDisplay/FixedIcon/fixedIcon.stories.tsx
src/dataDisplay/FixedIcon/images/networkError.tsx
src/dataDisplay/FixedIcon/index.tsx
src/inputs/Button/index.tsx

I have also added some space in the Button component to separate the icon from the text.

Feature: Add network error in FixedIcon

---

src/colors.stories.tsx
src/inputs/Link/index.stories.tsx
src/inputs/Link/index.tsx

feature: Add Link Component

---

src/dataDisplay/Card/index.tsx

Propagate props to Card component.

Pass extra props to Card

---

package.json
src/dataDisplay/Accordion/accordion.stories.tsx
src/dataDisplay/Accordion/index.tsx
src/dataDisplay/index.ts
yarn.lock

Closes https://github.com/gnosis/safe-react-components/issues/84.

Accordion component

---

src/dataDisplay/Accordion/index.tsx

add padding to chevron icon

---

src/navigation/Tab/index.tsx

(Fix) remove background color and center icons from Tabs component

---

src/navigation/Tab/index.tsx

Closed #90 
Add text-spacing according to the design provided.

(fix)Tab texts css

---

src/dataDisplay/Icon/index.tsx
src/dataDisplay/Tooltip/index.stories.tsx
src/dataDisplay/Tooltip/index.tsx
src/dataDisplay/index.ts

This component is required in SR for tx-v2.

Feature: Add Tooltip component

---

.github/workflows/lint.yml
package.json
yarn.lock

Add react 17 as valid peer dependency
Bump dependencies with minor changes

Add react 17 as valid peer dependency and upgrade dependencies

---

src/dataDisplay/Icon/index.tsx
src/inputs/Button/button.stories.tsx
src/inputs/Button/index.tsx
src/inputs/index.ts

Fix/Button: Fix styles and complete reimplementation

---

package.json
src/colors.stories.tsx
src/dataDisplay/Card/index.tsx
src/dataDisplay/FixedDialog/index.tsx
src/dataDisplay/Text/index.tsx
src/dataDisplay/Tooltip/index.tsx
src/inputs/Switch/index.tsx
src/utils/modals/GenericModal/index.tsx
yarn.lock

Remove direct dependency with polished library.
All tools used from polished have an equivalent in `material-ui` library

Remove polished dependency

---

src/dataDisplay/Tooltip/index.stories.tsx
src/dataDisplay/Tooltip/index.tsx

Closes #100
Also change the text color on Tooltip stories

Tooltip border color

---

src/inputs/Button/button.stories.tsx
src/inputs/Button/index.tsx

(Fix) Button styles

---

src/inputs/Button/index.tsx

(Fix) Buttons: Add background color on hover event.

---

src/theme.ts

add new color: errorTooltip

---

src/feedback/Loader/loader.stories.tsx
src/theme.ts

Related to https://github.com/gnosis/safe-react/pull/2119

feature: Add more sizes to Loader and add a new "pending" color

---

src/ethereum/EthHashInfo/index.tsx
src/ethereum/ExplorerButton/index.tsx
src/navigation/EllipsisMenu/index.tsx
src/utils/CopyToClipboardBtn/index.tsx

Add hover state to icons

---

.github/workflows/deploy-storybook.yml
.github/workflows/npm-publish.yml
package.json
src/inputs/AddressInput/AddressInput.stories.tsx
src/inputs/AddressInput/index.tsx
tests/inputs/AddressInput/__snapshots__/AddressInput.stories.storyshot

Added deploy storybook steps  in `npm-publish.yml`

Updated "Publish to NPM" Github Action to deploy storybook

---

.github/workflows/deploy-storybook.yml
package.json

Fixes a typo in static folder build name

Fix static folder naming in upload script

---

package.json
src/dataDisplay/Icon/icon.stories.tsx
src/dataDisplay/Icon/images/bookmark.tsx
src/dataDisplay/Icon/images/bookmarkFilled.tsx
src/dataDisplay/Icon/index.tsx
tests/dataDisplay/Accordion/__snapshots__/accordion.stories.storyshot
tests/dataDisplay/Card/__snapshots__/card.stories.storyshot
tests/dataDisplay/Dot/__snapshots__/dot.stories.storyshot
tests/dataDisplay/Icon/__snapshots__/icon.stories.storyshot
tests/dataDisplay/IconText/__snapshots__/index.stories.storyshot
tests/dataDisplay/Table/__snapshots__/table.stories.storyshot
tests/ethereum/EthHashInfo/__snapshots__/ethHashInfo.stories.storyshot
tests/ethereum/ExplorerButton/__snapshots__/index.stories.storyshot
tests/inputs/AddressInput/__snapshots__/AddressInput.stories.storyshot
tests/inputs/Button/__snapshots__/button.stories.storyshot
tests/inputs/ButtonLink/__snapshots__/buttonLink.stories.storyshot
tests/inputs/Link/__snapshots__/index.stories.storyshot
tests/inputs/TextField/__snapshots__/textField.stories.storyshot
tests/inputs/TextFieldInput/__snapshots__/TextFieldInput.stories.storyshot
tests/navigation/Breadcrumb/__snapshots__/breadcrumb.stories.storyshot
tests/navigation/Menu/__snapshots__/menu.stories.storyshot
tests/navigation/Stepper/__snapshots__/stepper.stories.storyshot
tests/navigation/Tab/__snapshots__/tab.stories.storyshot
tests/utils/CopyToClipboardBtn/__snapshots__/index.stories.storyshot

Add some missing icons for new transaction builder

feature: Add bookmark icons

---

src/revamp/theme/safeTheme.tsx

Implements typography style guide
https://www.figma.com/file/uqDJqIGikIB1zVs56XKnIu/Design-System---Web?node-id=203%3A67279

style: Adjust typography variants

---

.github/workflows/cla.yml
.github/workflows/deploy-storybook.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Add CLA signing action for contributors

Add CLA action

---

package.json
src/components/EthHashInfo/EthHashInfo.stories.tsx
src/components/EthHashInfo/index.tsx

Resolves a visual issue reported [here](https://github.com/safe-global/web-core/pull/1602#pullrequestreview-1282349543)

fix: Identicon visual issue

---

.github/workflows/deploy-storybook.yml
scripts/github/deploy_pull_request.sh

* Update the PR preview URL
* Remove manual Node.js and AWS installation, they are pre-installed in the image

Chore: update the deployment action

---

package.json
src/components/EthHashInfo/index.tsx
tests/src/components/AddressInput/__snapshots__/AddressInput.stories.storyshot
tests/src/components/ExplorerButton/__snapshots__/ExplorerButton.stories.storyshot
tests/src/theme/__snapshots__/Demo.stories.storyshot
yarn.lock

Update MUI and patch versions of other packages.

Chore: update dependencies
