safe-global/safe-react-components

src/inputs/TextField/index.tsx

- Add className props
- set 400px back as default width (it was a breaking change)

Fix: Textfield - add ClassName

---

src/utils/modals/GenericModal/index.tsx

I'm getting a sort of annoying messages when using the `GenericModal` component
I don't think they're necessary on production code.

(Chore) Remove `console.log` and `debugger`

---

src/ethereum/EthHashInfo/ethHashInfo.stories.tsx
src/ethereum/EthHashInfo/index.tsx
src/ethereum/EtherscanButton/index.stories.tsx
src/ethereum/EtherscanButton/index.tsx
src/ethereum/index.ts
src/utils/CopyToClipboardBtn/index.tsx

Refactor: AddressInfo and EtherscanButton

---

package.json
yarn.lock

Trying to run `yarn storybook` from a fresh `development` branch install fails:
After adding missing dependency it works

Storybook won't start without `file-loader` dependency installed

---

.eslintrc
src/inputs/TextField/index.tsx

This PR is to propagate `...rest` props to TextFieldMui Input.
Particularly I need to pass `onPaste` event, but this is a  generic solution.

propagate rest props to TextFieldMui

---

src/inputs/TextField/index.tsx

This PR aims to fix the background color defined for the input fields, according to the specs.

(Fix) `TextField` background-color

---

package.json
src/colors.stories.tsx
src/index.ts
yarn.lock

displays colors available in the theme
<kbd>![image](https://user-images.githubusercontent.com/3315606/89684448-d5346780-d8d0-11ea-8bb4-8b2c15e5c547.png)</kbd>

(Feature) Display colors with name and code

---

src/inputs/TextField/index.tsx
src/inputs/TextField/textField.stories.tsx

On `<TextField>` component, now `inputProps` are passed down to MUI component.
MUI reference https://material-ui.com/api/text-field/
With this change, `<TextField>` `input` props now can contain HTML props and properly pass it down to inner `<input>` element.
Added a Story for testing it with a `number` input with `min` and `max` set

Text field input props

---

src/dataDisplay/Accordion/accordion.stories.tsx
src/dataDisplay/Accordion/index.tsx
src/dataDisplay/index.ts

This is an enhancement over PR #85, by:
- Exporting a composable API (with `AccordionSummary`, `AccordionDetails` and `AccordionActions`)
- Preserving the overridden styles and setup defined in the SRC library
- Allowing using the MUI element's props

(Refactor) Accordion component

---

src/utils/CopyToClipboardBtn/index.tsx

This helps to fix https://app.zenhub.com/workspaces/safe-multisig---web-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/1976 since button as default is `submit` type

Fix - Add button role

---

src/theme.ts
src/utils/Identicon/index.stories.tsx

Now we have xl and xxl sizes for Identicon.

More sizes to Identicon component

---

src/dataDisplay/Accordion/index.tsx
src/inputs/Button/index.tsx

Some unwanted properties were passed down from React to DOM elements.
Fixed by renaming the props with a $ prefix to make them [Transient](https://styled-components.com/docs/api#transient-props).
* Run the storybook locally
* Open the Accordion
* Open the Button component
They should work like before and no warnings should be logged in the console.
I've also tested this version of safe-react-components with the safe-react locally, and it also doesn't show the warnings anymore ✅ 
Fixes #104 and fixes #105

Fix localProps & compact warnings

---

.github/workflows/test.yml
README.md
babel.config.js
package.json
src/navigation/Tab/tab.stories.tsx
tests/__snapshots__/storybook.test.js.snap
tests/jest-runtime.js
tests/storybook.test.js
yarn.lock

This PR adds simple regression testing based on Jest snapshots. They are automatically generated from the Storybook stories.
When changing a component implementation, this will help us find potential bugs.
What do you guys think?
Caveats:
* Portals have to be mocked (see `tests/jest-runtime.js`)
* The ScrollbarSize module from Material UI doesn't work in tests, so I had to replace the scrollable tabs with full-width tabs in the Tabs story.

Generate Jest snapshots from Storybook stories

---

src/dataDisplay/Icon/index.tsx
src/dataDisplay/IconText/index.stories.tsx
src/dataDisplay/IconText/index.tsx
src/navigation/Tab/index.tsx
src/theme.ts

Related to #109.
Every time we are using an icon + label in SR (safe-react) or SRC (safe-react-components) we need to add a css wrapper in order to align the text and the icon.
This component intends to fix that problem.
Its adds two new properties to `IconText`, side (left or right) and margin.
* side: used to indicate at what side the icon will be rendered. In SR, we use both icon + text for simple labels and text + icon for links. 
* margin: add some space between the icon and text.
As this repo only provides components and as we making use of [storybook](https://storybook.js.org/), it would be enough to have a story that represents all the variants for each component. In the PR description, you will find a link to a deployed instance of `storybook`. For this particular PR the link is …

feature: Add margin and side props to IconText 

---

src/ethereum/EthHashInfo/ethHashInfo.stories.tsx
src/ethereum/EthHashInfo/index.tsx
tests/__snapshots__/storybook.test.js.snap

Feature: EthHasInfo add showHash property

---

package.json
tests/__snapshots__/storybook.test.js.snap
tests/jest-runtime.js
yarn.lock

Fixes #122
The `jest-styled-components` library replaces the randomly generated styled-components classes with simple counter-based class names. This makes the snapshots 100% predictable.

Fix the tests: make classnames deterministic

---

src/ethereum/EthHashInfo/ethHashInfo.stories.tsx
src/ethereum/EthHashInfo/index.tsx
tests/__snapshots__/storybook.test.js.snap

We need to handle the case for when `customAvatar` is broken.
- I added a new property called `customAvatarFallaback` that receives an URL to callback in case the main image is broken
- I no `customAvatarFallaback` was provided it fallback to Identicon.
These changes are needed for https://app.zenhub.com/workspaces/safe-multisig---web-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/2133

feature: EthHashInfo add customAvatar fallback

---

src/dataDisplay/FixedDialog/index.tsx
src/utils/modals/utils.tsx
tests/__snapshots__/storybook.test.js.snap

Closes #118 
Related to https://github.com/gnosis/safe-react/issues/2189
Backgound removed and styles fixes.

FixedDialog component styles

---

src/inputs/Checkbox/index.tsx

Since MaterialUI supports passing a `node` as `label`, we consider it important to add support for the checkbox component to receive a node for `label` prop

Feature - Checkbox label supports passing a node

---

src/dataDisplay/Table/index.tsx
tests/__snapshots__/storybook.test.js.snap

Closes #128.
Sorting doesn't work if you don't pass `onHeaderClick`, so no need to show the arrow icon in this case.

Table: don't show the sorting arrow when no sorting fn passed

---

src/dataDisplay/Icon/images/collectibles.tsx
tests/__snapshots__/storybook.test.js.snap

The diamond icon is a bit too large compared to the other icons. I've made it a bit smaller so that it better fits in the sidebar menu.
Before | After
-------|------
In the storybook:

Downscale the collectibles icon

---

src/dataDisplay/Table/index.tsx
src/dataDisplay/Table/table.stories.tsx
tests/__snapshots__/storybook.test.js.snap

This PR adds a small feature to the Table component.
Adds two new properties: **maxHeight** and **isStickyHeader** 
If both are set and the table contents exceed maxHeight, the header stays fixed to the top and only the rows are scrolled.
see #137

Adds support for fixed/sticky table header

---

src/utils/CopyToClipboardBtn/index.stories.tsx
src/utils/CopyToClipboardBtn/index.tsx
tests/utils/CopyToClipboardBtn/__snapshots__/index.stories.storyshot

[Transaction deeplinking](https://github.com/gnosis/safe-react/issues/970) preparation
The option of selecting the `<CopyToClipboardBtn>` icon `type` is now possible via props.

Add icon type selection to copy component

---

.github/workflows/deploy-storybook.yml
package.json

There was one step missing on CI so we were able to upload production files in order to be deployed to the correct environment.

Add step to upload production build

---

.github/workflows/release.yml

Publishing to NPM w/o 2FA is a security concern, so we're removing this.

Chore: rm automatic NPM publising

---

src/ethereum/EthHashInfo/index.tsx

In order to conform with the redesign of Tx Modals the name in `EthHashInfo` should be bold.

style: Adjust EthHashInfo name font weight

---

package.json
src/inputs/AddressInput/index.tsx
src/inputs/Select/index.tsx
src/inputs/TextFieldInput/TextFieldInput.stories.tsx
src/inputs/TextFieldInput/index.tsx
src/inputs/styles.ts
tests/inputs/AddressInput/__snapshots__/AddressInput.stories.storyshot
tests/inputs/Select/__snapshots__/select.stories.storyshot
tests/inputs/TextFieldInput/__snapshots__/TextFieldInput.stories.storyshot
tests/navigation/Tab/__snapshots__/tab.stories.storyshot

The AddressInput component is removing the network prefix on paste. This is because the changes in the major 1.0.0 so we remove the specific change and use a workaround to get the same visual behavior
We fix the disabled state as well on selects as did not match the designs

Fix <AddressInput /> component

---

package.json
src/dataDisplay/Icon/images/bookmark.tsx
src/dataDisplay/Icon/images/bookmarkFilled.tsx
tests/dataDisplay/Icon/__snapshots__/icon.stories.storyshot

The stroke in the bookmark icons is too tiny when sm and vivid colors

fix: Stroke in bookmark icons

---

package.json
src/inputs/ButtonLink/index.tsx

Allow children to be optional in ButtonLink, allowing to create a button with only icon

Allow optional children in ButtonLink

---

babel.config.js
package.json
src/inputs/AddressInput/index.tsx
webpack.config.js

To avoid a mini infinite loop I'm facing in transaction builder I added a check for address/input value equality before firing `updateAddressState`.
The mini infinite loop looks like following:
1. `address` (passed from controlling component) = '', `inputValue` = "ABC" --> `onChangeAddress` is called
2. `address` (passed from controlling component) = 'ABC', `inputValue` = "ABC" --> `updateAddressState` is called because `address` has changed, and it calls `onChangeAddress` again
I also disabled webpack minimizing because this is a developer-facing library and it's way cooler to debug non-minified code

Check if the current state address equals input value before updating address state

---

package.json
src/theme/safeTheme.tsx

When using a link inside of tooltips the theme makes the link unreadable in light-mode.
This PR fixes the colors of links to the correct ones when embedded in a tooltip.

fix: link color in tooltips

---

package.json
src/components/EthHashInfo/EthHashInfo.stories.tsx
src/components/EthHashInfo/index.tsx
src/components/ExplorerButton/index.tsx
tests/src/components/ExplorerButton/__snapshots__/ExplorerButton.stories.storyshot

I've added stopPropagation on the etherscan link. It's needed for the NFTs page which opens an NFT preview on the parent element click.
Also added some tiny optimizations in the code.

Fix: add stopPropagation to the external link

---

.github/workflows/release.yml

When generating a changelog, it was taking the previous version from the latest publish package on NPM.
It should take the latest tag instead.

Fix: previous version detection in release automation

---

.storybook/webpack.config.js
package.json
src/components/EthHashInfo/CopyButton.tsx
src/components/ExplorerButton/index.tsx

In web-core, there's a key warning whenever either the ExplorerButton or the CopyButton is rendered.
The Tooltip component thinks we're passing an array for some reason. I gave its children a key so that it's happy...
I've also simplified the storybook webpack config.

Fix: "unique key" warnings in Tooltips
